In [1]:
from db import create_mysql_engine_from_env

In [2]:
engine = create_mysql_engine_from_env()

## Check Connection

In [3]:
import pandas as pd
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE() AS database_name"))
    print(result.fetchone())

('cars_analysis',)

In [4]:
query = """
SELECT
    COUNT(*) AS listing_count
FROM vehicle_listings;
"""

pd.read_sql_query(query, engine)

   listing_count
0         100000

In [5]:
query = """
SELECT
    vl.listing_id,
    vl.price,
    v.year,
    m.manufacturer_name,
    vm.model_name,
    vl.odometer,
    s.state_code,
    r.region_name
FROM vehicle_listings vl
JOIN vehicles v ON v.vehicle_id = vl.vehicle_id
LEFT JOIN manufacturers m ON m.manufacturer_id = v.manufacturer_id
LEFT JOIN vehicle_models vm ON vm.model_id = v.model_id
JOIN regions r ON r.region_id = vl.region_id
LEFT JOIN states s ON s.state_id = r.state_id
LIMIT 10;
"""

pd.read_sql_query(query, engine)

,listing_id,price,year,manufacturer_name,model_name,odometer,state_code,region_name
0,7301656000,40988,2019,ford,f-150,29506,ak,anchorage / mat-su
1,7301741980,14900,1985,toyota,celica gt-s convertible,96551,ak,anchorage / mat-su
2,7301742033,39900,2017,rover,evoque convertible hse dynamic,56809,ak,anchorage / mat-su
3,7301742102,26900,2014,mercedes-benz,e 350,44992,ak,anchorage / mat-su
4,7301742154,34900,2015,jaguar,xjl portfolio,16192,ak,anchorage / mat-su
5,7301754515,13995,2014,mini,paceman,88215,ak,anchorage / mat-su
6,7301754541,19995,2013,jeep,wrangler,95446,ak,anchorage / mat-su
7,7301754574,10495,2016,ford,c-max hybrid,71835,ak,anchorage / mat-su
8,7301754606,15995,2013,bmw,x5,120867,ak,anchorage / mat-su
9,7301754635,28995,2020,hyundai,santa fe,23500,ak,anchorage / mat-su

In [8]:
from db import create_mysql_engine_from_env, get_vehicle_listings

engine = create_mysql_engine_from_env()

df = get_vehicle_listings(
    engine,
    min_price=10000,
    max_price=30000,
    min_year=2015,
    manufacturer="honda",
    state="co",
    limit=100,
)

df.head()

,listing_id,price,year,manufacturer,model,odometer,fuel_type,transmission,title_status,vehicle_condition,drive_type,vehicle_type,paint_color,state,region,latitude,longitude,posting_date,listing_url
0,7316924911,18990,2017,honda,accord lx sedan 4d,30317,gas,other,clean,good,fwd,sedan,white,co,denver,39.760000,-104.870000,2021-05-04 14:31:23,https://denver.craigslist.org/ctd/d/denver-201...
1,7316924707,18990,2017,honda,accord lx sedan 4d,31488,gas,other,clean,good,fwd,sedan,red,co,denver,39.760000,-104.870000,2021-05-04 14:31:05,https://denver.craigslist.org/ctd/d/denver-201...
2,7316895886,18990,2019,honda,fit sport hatchback 4d,17195,gas,other,clean,good,fwd,hatchback,red,co,denver,39.760000,-104.870000,2021-05-04 13:41:28,https://denver.craigslist.org/ctd/d/denver-201...
3,7316719428,17990,2015,honda,civic ex-l sedan 4d,32385,gas,other,clean,good,fwd,sedan,white,co,fort collins / north CO,40.550000,-105.060000,2021-05-04 09:01:13,https://fortcollins.craigslist.org/ctd/d/fort-...
4,7316696086,13829,2015,honda,accord sedan,74226,gas,automatic,clean,NaN,fwd,sedan,NaN,co,colorado springs,38.819649,-104.758553,2021-05-04 08:19:51,https://cosprings.craigslist.org/ctd/d/colorad...